const HtmlWebpackPlugin = require("html-webpack-plugin");
const webpack = require("webpack");

/** @type { import('webpack').Configuration } */
module.exports = {
  mode: "development",
  entry: {
    theme: "./src/theme.js",
    main: [
      "webpack-dev-server/client?hot=true&live-reload=true&overlay=true",
      "webpack/hot/dev-server",
      "./src/index.js",
    ],
  },
  plugins: [new HtmlWebpackPlugin(), new webpack.HotModuleReplacementPlugin()],

  // simplifies testing the problem
  output: {
    clean: true,
  },
  devtool: false,
  devServer: {
    client: false,
    hot: false,
    compress: false,
    // write dist generated by WDS to inspect
    devMiddleware: {
      writeToDisk: true,
    },
  },
};
